version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: frontend 
    ports:
      - '3000:3000'
    env_file: ./.env 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres 

  postgres:
    image: postgres:17
    container_name: postgresql_server
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME} 
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: -p 5432

volumes:
  pgdata:


