import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navigation/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { ListOfNavItems } from "./_components/navigation/ListOfNavItem";
import Navitem from "./_components/navigation/Navitem";
import SignOut from "./_components/navigation/SignOut";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/navigation/AppSidebar";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="p-10">
      <body className={cn(inter.className, "bg-[rgb(36,37,38)]")}>
        <SidebarProvider>
          <Navbar />
          <AppSidebar />
          <main className="mt-[4rem] mx-auto text-white">
            {children}
            <Toaster />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}

{
  /* Sidebar */
}
{
  /* <div className="hidden md:flex fixed top-[5.9rem] left-0 bottom-0 flex-col items-center w-[15rem] justify-betweem gap-8 bg-gray-500">
  {ListOfNavItems.map((navItem) => {
    return (
      <Navitem
        key={navItem.href}
        name={navItem.name}
        href={navItem.href}
        active={navItem.active}
        icon={navItem.icon}
      />
    );
  })}
  <SignOut />
</div> */
}
