import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navigation/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cn } from "@/lib/utils";
import dynamic from "next/dynamic";
import { AppSidebar } from "./_components/navigation/AppSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="p-10">
      <body className={cn(inter.className, "bg-[rgb(36,37,38)]")}>
        <SidebarProvider>
          <Navbar />
          <AppSidebar />
          <main className="mt-[4rem] mx-auto text-white flex flex-col min-h-screen w-full justify-center items-center">
            <div className="flex-1 w-full max-w-[800px]">{children}</div>
            <Toaster />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
