import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navigation/Navbar";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="p-10">
      <body className={inter.className}>
        <main className="flex flex-col justify-center">
          <Navbar />
          <div className="mt-20 flex items-center justify-center">
            {children}
          </div>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
