export enum SearchPostType {
  USER_POST = 1,
  ALL_POST = 2,
  SEARCH_POST = 3,
  USER_FAVOURITE_POST = 4,
}

export enum NotificationType {
  LIKE_POST = "LIKE_POST",
  LIKE_COMMENT = "LIKE_COMMENT",
  LIKE_REPLY_COMMENT = "LIKE_REPLY_COMMENT",
  POST = "POST",
  COMMENT = "COMMENT",
  COMMENT_REPLY = "COMMENT_REPLY",
  FOLLOW = "FOLLOW",
}
